import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  hooksSidebar: [
    'intro',
    'hooks/getting-started',
    {
      type: 'category',
      label: 'State & Data',
      items: [
        'hooks/state-data/use-toggle',
        'hooks/state-data/use-disclosure',
        'hooks/state-data/use-counter',
        'hooks/state-data/use-list',
        'hooks/state-data/use-map',
        'hooks/state-data/use-set',
        'hooks/state-data/use-history-state',
        'hooks/state-data/use-default',
        'hooks/state-data/use-queue',
        'hooks/state-data/use-stack',
        'hooks/state-data/use-local-storage',
        'hooks/state-data/use-session-storage',
        'hooks/state-data/use-uncontrolled',
      ],
    },
    {
      type: 'category',
      label: 'Values & Memoization',
      items: [
        'hooks/values-memoization/use-debounce',
        'hooks/values-memoization/use-debounced-callback',
        'hooks/values-memoization/use-throttle',
        'hooks/values-memoization/use-throttled-callback',
        'hooks/values-memoization/use-previous',
        'hooks/values-memoization/use-latest',
        'hooks/values-memoization/use-const',
        'hooks/values-memoization/use-synced-ref',
      ],
    },
    {
      type: 'category',
      label: 'DOM & Browser',
      items: [
        'hooks/dom-browser/use-click-outside',
        'hooks/dom-browser/use-event-listener',
        'hooks/dom-browser/use-element-size',
        'hooks/dom-browser/use-hover',
        'hooks/dom-browser/use-key-press',
        'hooks/dom-browser/use-key-combo',
        'hooks/dom-browser/use-long-press',
        'hooks/dom-browser/use-fullscreen',
        'hooks/dom-browser/use-text-selection',
        'hooks/dom-browser/use-focus-within',
        'hooks/dom-browser/use-focus-trap',
        'hooks/dom-browser/use-bounding-client-rect',
        'hooks/dom-browser/use-swipe',
        'hooks/dom-browser/use-drag',
        'hooks/dom-browser/use-element-visibility',
        'hooks/dom-browser/use-scroll-position',
        'hooks/dom-browser/use-scroll-lock',
        'hooks/dom-browser/use-mutation-observer',
        'hooks/dom-browser/use-intersection-observer',
      ],
    },
    {
      type: 'category',
      label: 'Timers & Lifecycle',
      items: [
        'hooks/timers-lifecycle/use-interval',
        'hooks/timers-lifecycle/use-timeout',
        'hooks/timers-lifecycle/use-countdown',
        'hooks/timers-lifecycle/use-stopwatch',
        'hooks/timers-lifecycle/use-idle-timer',
        'hooks/timers-lifecycle/use-update-effect',
        'hooks/timers-lifecycle/use-isomorphic-layout-effect',
        'hooks/timers-lifecycle/use-is-mounted',
        'hooks/timers-lifecycle/use-is-first-render',
      ],
    },
    {
      type: 'category',
      label: 'Async & Network',
      items: [
        'hooks/async-network/use-fetch',
        'hooks/async-network/use-async',
        'hooks/async-network/use-script',
        'hooks/async-network/use-web-socket',
        'hooks/async-network/use-sse',
        'hooks/async-network/use-polling',
        'hooks/async-network/use-abort-controller',
        'hooks/async-network/use-retry',
        'hooks/async-network/use-search',
      ],
    },
    {
      type: 'category',
      label: 'Browser APIs',
      items: [
        'hooks/browser-apis/use-media-query',
        'hooks/browser-apis/use-dark-mode',
        'hooks/browser-apis/use-color-scheme',
        'hooks/browser-apis/use-copy-to-clipboard',
        'hooks/browser-apis/use-online',
        'hooks/browser-apis/use-window-size',
        'hooks/browser-apis/use-page-visibility',
        'hooks/browser-apis/use-page-leave',
        'hooks/browser-apis/use-favicon',
        'hooks/browser-apis/use-reduced-motion',
        'hooks/browser-apis/use-breakpoint',
        'hooks/browser-apis/use-is-client',
      ],
    },
    {
      type: 'category',
      label: 'Layout & UI',
      items: [
        'hooks/layout-ui/use-sticky-header',
        'hooks/layout-ui/use-virtual-list',
        'hooks/layout-ui/use-infinite-scroll',
        'hooks/layout-ui/use-collapse',
        'hooks/layout-ui/use-steps',
      ],
    },
  ],
};

export default sidebars;
